version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - Duuun
  versioning-strategy: lockfile-only
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: mimemagic
    versions:
    - 0.3.10
    - 0.3.6
    - 0.3.7
    - 0.3.9
  - dependency-name: mini_mime
    versions:
    - 1.0.3
  - dependency-name: bootsnap
    versions:
    - 1.7.3
  - dependency-name: nokogiri
    versions:
    - 1.11.1
    - 1.11.2
  - dependency-name: i18n
    versions:
    - 1.8.7
    - 1.8.9
  - dependency-name: rails
    versions:
    - 6.0.3.4
    - 6.0.3.5
  - dependency-name: loofah
    versions:
    - 2.9.0
  - dependency-name: tzinfo
    versions:
    - 1.2.9
  - dependency-name: zeitwerk
    versions:
    - 2.4.2
